debian-vm/debian/control
One of fixes for QubesOS/qubes-issues#2608
=> Fix Depends for trusty build

patches.misc/mini-os-link-to-libgcc.a-to-fix-build-with-gcc7.patch, patches.misc/stubdom-fix-vtpm-compilation-on-GCC-7.patch, patches.misc/tools-misc-xenlockprof-fix-possible-format-string-overflow.patch, patches.misc/v2-tools-fix-several-format-truncation-warnings-with-GCC-7.patch, patches.misc/vtpmmgr-make-inline-functions-static.patch, series.conf
=> Fix GCC7 warnings/errors

patches.misc/hvmpt02-disable-msix-caps.patch, patches.qubes/stubdom-allow-msi-enable.patch, patches.qubes/stubdom-allow-msi-irq.patch, series.conf
This depends on QubesOS/qubes-linux-kernel#12
=> Add MSI support for stubdoms

archlinux/PKGBUILD
=> Fix patches path to make Arch Linux PKGBUILD work again

patch-f97838bb-x86-Move-microcode-loading-earlier.patch, xen.spec
With those patches the microcode update is loaded before testing for
hardware features.
=> Add upstream patches for improved early microcode loading

patch-866dedab-x86-PV-also-cover-Dom0-in-SPEC_CTRL-PRED_CMD-emulati.patch, patch-da926644-x86-spec_ctrl-Fix-several-bugs-in-SPEC_CTRL_ENTRY_FR.patch, patch-x86-check-feature-flags-after-resume.patch, patch-x86-correct-ordering-of-operations-during-S3-resume.patch, patch-x86-suppress-BTI-mitigations-around-S3-suspend-resum.patch, xen.spec.in
Also add a few other spec ctrl fixes from staging.
QubesOS/qubes-issues#3738
=> Fix resume when using microcode update

Makefile.builder, xen.spec.in
Related to https://github.com/QubesOS/qubes-issues/issues/1508
=> Handle sources archives for submodules/subfolders

Makefile
(cherry picked from commit e414a753f74f9a8f40fea0c9efae65a6fd1d9e13)
=> Allow setting DISTFILES_MIRROR in the builder.conf

debian-vm/debian/control
Also remove otiose reference to zesty
=> Allow build for artful in 4.0

.travis.yml, debian-quilt, debian-vm/debian/control, xen.spec.in
https://github.com/QubesOS/qubes-issues/issues/816
https://github.com/QubesOS/qubes-issues/issues/2775
=> Fixes for reproducible builds

series-vm.conf
Related to https://github.com/QubesOS/qubes-vmm-xen/pull/58
=> Add GCC patch to fix archlinux template building

patch-libxl-disable-vkb-by-default.patch, patch-stubdom-linux-libxl-suspend.patch, xen.spec.in
- fix suspend
- don't enable vkb device
=> Fixes to libxl

patch-4.13-0001-x86-amd-Avoid-cpu_has_hypervisor-evaluating-true-on-.patch, xen.spec.in
Fixes QubesOS/qubes-issues#5644
=> Apply fix for HYPERVISOR bit in calculated CPUID - fix resume on AMD

patch-xen-gcc10-fixes.patch, patch-xen-ocaml-4.10.patch, patch-xen-pygrubfix.patch, xen.spec.in
https://github.com/QubesOS/qubes-issues/issues/5763
=> Add gcc10, ocaml4.10 and pygrub fixes from Fedora

.gitlab-ci.yml, patch-0001-crypto-adjust-rijndaelEncrypt-prototype-for-gcc11.patch, patch-xen.gcc11.fixes.patch, series-vm.conf, xen.spec.in
=> More GCC11 fixes

xen.spec.in
This fixes missing xen.efi while OS setup
=> add R coreutils to fix initial post install action

patch-libxl-Fix-QEMU-cmdline-for-scsi-device.patch, xen.spec.in
Necessary for QubesOS/qubes-vmm-xen-stubdom-linux#40
=> Backport changes necessary for QEMU 6.x in stubdomain

Makefile.builder
https://github.com/QubesOS/qubes-issues/issues/7134
=> Add Debian bookworm support

patch-libxl-Replace-deprecated-QMP-command-by-query-cpus-f.patch, xen.spec.in
Fixes QubesOS/qubes-issues#7175
=> Backport one more patch for updated qemu

patch-IOMMU-x86-work-around-bogus-gcc12-warning-in-hvm_gsi.patch, patch-ns16550-add-more-device-IDs-for-Intel-LPSS-UART.patch, patch-ns16550-add-support-for-Intel-LPSS-UART.patch, patch-ns16550-use-poll-mode-if-INTERRUPT_LINE-is-0xff.patch, patch-x86-CPUID-surface-suitable-value-in-EBX-of-XSTATE-su.patch, patch-x86-deal-with-gcc12-release-build-issues.patch, series-debian-vm.conf, series-vm.conf, xen.spec.in
Debugging Xen on laptops is hard, backport patches that adds more console
options.
=> Add more console options

patch-xen-sched-migrate-timers-to-correct-cpus-after-suspe.patch, xen.spec.in
=> Backport timers migration fix

0627-x86-mm-Avoid-hard-coding-PAT-in-get_page_from_l1e.patch, 0628-x86-mm-make-code-robust-to-future-PAT-changes.patch, 1019-Use-Linux-s-PAT.patch, xen.spec.in
Work around a nasty hardware erratum.
=> Use Linux's PAT

0500-x86-Activate-Data-Operand-Invariant-Timing-Mode-by-d.patch, xen.spec.in
=> Activate Data Operand Independent Timing Mode by default

0629-tools-python-change-s-size-type-for-Python-3.10.patch, xen.spec.in
=> Add patch for Python >= 3.10 support

0311-x86-cpuid-Infrastructure-for-leaves-7-1-ecx-edx.patch, 0312-x86-shskt-Disable-CET-SS-on-parts-succeptable-to-fra.patch, xen.spec.in
See patches description for detail.
=> Backport workaround for broken CET-SS on some parts

0651-x86-msi-passthrough-all-MSI-X-vector-ctrl-writes-to-.patch, 0652-x86-hvm-Allow-writes-to-registers-on-the-same-page-a.patch, xen.spec.in
Fixes QubesOS/qubes-issues#4799
Fixes QubesOS/qubes-issues#7057
Fixes QubesOS/qubes-issues#7052
=> Apply patches for MSI-X support with stubdomain

xen.logrotate
They may grow quite big in some cases, and are very compressible.
=> Compress old console logs

0314-drivers-char-support-up-to-1M-BAR0-of-xhci.patch, 0653-libxl-Disable-relocating-memory-for-qemu-xen-in-stub.patch, xen.spec.in
This supersedes #172
cc @neowutran
=> Backport XHCI console for AMD and hvmloader fix

0315-amd-vi-fix-IVMD-memory-type-checks.patch, xen.spec.in
=> Backport IVMD fix

0315-IOMMU-store-name-for-extra-reserved-device-memory.patch, 0316-drivers-char-mark-extra-reserved-device-memory-in-me.patch, xen.spec.in
See patch description for details.
Fixes QubesOS/qubes-issues#9030
=> Backport a fix for XHCI console

archlinux/PKGBUILD.in
Fix xendriverdomain service, needed for providing network and block backends.
=> Fixes for Arch
