QubesOS/qubes-vmm-xen

patches.qubes/stubdom-linux-pci-add-del.patch
Use qemu_pci_{add,remove}_xenstore as used for minios stubdoms instead
of triggering on new PCI devices inside the stubdom. This way we have
the same timing behavior as with minios stubdoms or qemu in dom0. As a
bonus this makes the patch smaller.
BTW: Fix logic in remove case.
=> stubdom-linux: rework pci add/remove handling

patches.misc/v2-0001-VT-d-don-t-panic-warn-on-iommu-no-igfx.patch, series.conf
~~[Submitted to xen-devel](https://lists.xen.org/archives/html/xen-devel/2017-07/msg02799.html), but no response so far.~~ [v2 patch](https://lists.xen.org/archives/html/xen-devel/2017-07/msg03065.html) prints an info message. ~~(Not that it's urgent, but it might make sense to include this in the next .iso.)~~ oh
=> Hypervisor patch "VT-d: don't panic/warn on iommu=no-igfx"

patches.qubes/stubdom-linux-0005.patch, patches.qubes/stubdom-linux-libxl-do-not-force-qdisk-backend-for-cdrom.patch, patches.qubes/stubdom-linux-libxl-don-t-try-to-resolve-local-disk-path-with-stub.patch, series.conf
There were a couple of checks in libxl preventing cdrom usage with qemu-xen in
linux-stubdom. Those patches removes the check. And most likely break
qemu-in-dom0 usage with cdrom, or at least make error messages for invalid
configuration much less informative. But we don't support qemu in dom0.
Fixes QubesOS/qubes-issues#2951
=> Allow starting a VM with cdrom attached

patches.qubes/stubdom-linux-0005.patch, xen.spec
The 'mptsas1068' scsi controller seems to work fine with Windows (QubesOS/qubes-issues#3068) and Linux (if you assign some WWNs to the disks). So switch to it. Since this requires a newer SeaBIOS for booting this PR depends on QubesOS/qubes-vmm-xen-stubdom-linux#5.
This breaks booting with UEFI. But given that we don't use this anywhere yet, the Windows support is more important. Fixing the UEFI support is probably not hard since it can use the disk and boots if you manually enter the path of the grub exe. But for some reason it don't want to automatically start it.
=> Switch scsi controller

archlinux/PKGBUILD, series-vm.conf
I've just fixed the archlinux PKGBUILD script and removed the missing (obsolete?) Xen patches. The problem is that I don't know that much about Xen (and consequently what exactly I am doing here ) :smile: ...
It seems that the archlinux build uses [`series-vm.conf`](https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.8/series-vm.conf) patches while fedora uses the much bigger [`series.conf`](https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.8/series.conf) patchlist... So at first I attempted to use it in the archlinux build as well. That resulted in strange errors like `make[7]: *** No rule to make target '/usr/share/ipxe/10ec8139.rom', needed by 'roms.inc'.  Stop.`.  After a while messing around and trying to understand what the issues were, I decided to try using `series-vm.conf` with …
=> Archlinux template fixes for QubesOS 4.0

patches.security/xsa254-44ad7f68-x86-allow-Meltdown-band-aid-to-be-disabled.patch, patches.security/xsa254-91dc902f-x86-Meltdown-band-aid-against-malicious-64-bit-PV-gu.patch, patches.security/xsa254-a065841b-x86-mm-Always-set-_PAGE_ACCESSED-on-L4e-updates.patch, patches.security/xsa254-c6e9e609-x86-entry-Remove-support-for-partial-cpu_user_regs-f.patch, series.conf
From XSA 254 v9.
That's an alternative option to QubesOS/qubes-core-admin#178
The performance penalty seems to be **roughly** 20..25 %. Will post detailed numbers later.
=> Add "stage 1" PTI patches against Meltdown

patches.misc/96edb111-libxc-panic-when-trying-to-create-a-PVH-guest-withou.patch, patches.misc/libxc-panic-when-trying-to-create-a-PVH-guest-withou.patch, series.conf
QubesOS/qubes-issues#3474
---
With this change the message is a good bit clearer, although the "No such file or directory" is still a bit irritating.
2018-01-18 20:42:47.735+0000: xc: panic: xc_dom_elfloader.c:66: xc_dom_guest_type: image not capable of booting inside a HVM container: Invalid kernel
2018-01-18 20:42:47.735+0000: xc: panic: xc_dom_core.c:734: xc_dom_set_arch_hooks: not found (type xen-3.0-unknown): Invalid kernel
2018-01-18 20:42:47.735+0000: xc: panic: xc_dom_core.c:944: xc_dom_mem_init: arch hooks not set: Internal error
2018-01-18 20:42:47.735+0000: libxl: libxl_dom.c:649:libxl__build_dom: xc_dom_mem_init failed: No such file or directory
2018-01-18 20:42:47.741+0000: libxl: libxl_create.c:1266:domcreate_rebuild_done: cannot (re-)build domain: -3
=> Backport elfloader fix to detect non PVH capable kernels

patch-stubdom-linux-0005.patch
For the original uhci controller emulated by qemu, linux guests won't automatically enable usb autosuspend, unless udev 42-usb-hid-pm.rules is present in the guest OS, resulting resulting in increased idle cpu consumption (issue QubesOS/qubes-issues#2849). Changing the usb controller to ehci resolves this without guest modification. This patch also removes the ifup/ifdown scripts, to allow seccomp to be enhanced.
=> Change emulated qemu usb controller to ehci

xen.spec.in
Prior to this commit, Xen EFI binary would be installed into the EFI partition as "xen-4.8.5-4.fc25.efi", whereas prior to commit abf64bdeb9 ("rpm: export the same env variable during build and install"), the file name did not have the package release suffix (i.e., "-4.fc25"). The existence of the package release suffix in the file name causes the RPM installation scripts to fail to copy the binary to xen.efi in the EFI partition.
To avoid the aforementioned issue, this commit uses the release provided by RPM in the hypervisor package's post-installation script for the naming of the EFI binary as well.
=> rpm: Be consistent with EFI binary name

patch-xen-acpi-slic-support.patch, xen.spec.in
This patch from OpenXT to update OEM and OEM ID signatures if SLIC table was defined. It is necessary to activate OEM media installed Windows.
=> add patch to additional support in ACPI builder SLIC and OEM installs

xen.spec.in
Currently it fails to build with binutils-2.32-26.fc31.x86_64 but the build with newer 2.33+ version is fine. It should be soon in Fedora 31 repo.
=> spec: fix missing dependencies for Fedora 31

patch-xen-disable-efi-gettime.patch, xen.spec.in
The patch is used by many Xen-based projects for a long time already.
Details here: https://lists.gt.net/xen/devel/408709
=> Disable commonly broken EFI GetTime() call

patch-libxl-console.patch, xen.spec.in
Upstream: xen-project/xen@0d99c909d7e1cbe69329a00f7772946f10a7865b
Fixes QubesOS/qubes-issues#5156.
=> libxl: wait for console path before firing console_available

xen.spec.in
Qubes R4.1 use grant tables a lot for mapping GUI windows, increase
default limits to allow that. This is especially important, as in case
of grant table entries shortage, other users (PV drivers, including disk
and network) will also fail.
Fixes QubesOS/qubes-issues#5674
Fixes QubesOS/qubes-issues#5519
=> Increase default gnttab_max_frames and gnttab_max_maptrack_frames

xen.spec.in
mingw64-binutils is currently removed from EPEL due to
several CVE issues (see https://bugzilla.redhat.com/show_bug.cgi?id=1807975
and https://pagure.io/fesco/issue/2333).
=> Currently disable building EFI for CentOS 7

debian-vm/debian/rules, patch-0001-libxl-devd-fix-a-race-with-concurrent-device-additio.patch, patch-0002-libxl-devd-correctly-manipulate-the-dguest-list.patch, series-debian-vm.conf, series-vm.conf, xen.spec.in
Hello,
The topmost commit in this pull request resolves [QubesOS issue 4784](https://github.com/QubesOS/qubes-issues/issues/4784). I have verified this with a Fedora 30-based sys-usb VM on Qubes OS 4.0 only, but the commits also modify the patch series files for Debian buster (verified to compile) and ArchLinux (not verified at all).
For the record, the backported commits should already be present in the upstream version of Xen 4.13, so this pull request is specific to the xen-4.8 branch of the vmm-xen repository.
The debugging symbol enablement commit, while not directly relevant, is included in this pull request to make future debugging exercises more efficient.
Thanks!
=> Resolve errors involving detaching multiple block devices

patch-libxl-automatically-enable-gfx_passthru-if-IGD-is-as.patch, xen.spec.in
See patch description for details
QubesOS/qubes-issues#2618
=> Automatically enable gfx_passthru option when needed

patch-0001-xen-sched-call-cpu_disable_scheduler-via-cpu-notifie.patch, patch-0002-xen-add-helper-for-calling-notifier_call_chain-to-co.patch, patch-0003-xen-add-new-cpu-notifier-action-CPU_RESUME_FAILED.patch, patch-0004-xen-don-t-free-percpu-areas-during-suspend.patch, patch-0005-xen-cpupool-simplify-suspend-resume-handling.patch, patch-0006-x86-ACPI-re-park-previously-parked-CPUs-upon-resume-.patch, patch-0007-sched-populate-cpupool0-only-after-all-cpus-are-up.patch, patch-0008-x86-clear-per-cpu-stub-page-information-in-cpu_smpbo.patch, patch-0009-x86-S3-put-data-segment-registers-into-known-state-u.patch, xen.spec.in
This pull request intends to resolve QubesOS/qubes-issues#5210 by cherry-picking 9 commits to the version of Xen 4.8 shipped by Qubes OS, so that unused CPU hyperthreads are parked during the resume from suspend-to-RAM. For information about how this pull request was verified to resolve this issue, please see the commit message.
The 9th patch is a bit special and is required to resolve intermittent segmentation faults encountered by `systemd-sleep` (after applying the first 8 patches) during the resume from suspend-to-RAM; more details about this patch can be found in the commit message as well.
=> Park unused CPU threads after suspend-to-RAM

patch-Revert-xen-credit2-limit-the-max-number-of-CPUs-in-a.patch, patch-x86-S3-Fix-Shadow-Stack-resume-path.patch, patch-x86-S3-Restore-CR4-earlier-during-resume.patch, patch-x86-smpboot-Unconditionally-call-memguard_unguard_stack.patch, xen.spec.in
Fixes QubesOS/qubes-issues#6066
=> Fix S3 resume

archlinux/PKGBUILD, debian-vm/debian/control, debian-vm/debian/rules, debian-vm/debian/scripts/xen-init-list, debian-vm/debian/scripts/xen-init-name
There is no point in keeping python2 support anymore.
For Debian bullseye, 'python' package is not installable anymore (there
is 'python2' but we don't want to go this way).
QubesOS/qubes-issues#5297
=> deb, arch: migrate to python3 completely

archlinux/PKGBUILD, patch-libxl-cleanup-remaining-backend-xs-dirs-after-driver.patch, xen.spec.in
Driver domain is responsible for xenstore cleanup, but it doesn't have
access to remove (empty) parent directory. Do it in toolstack domain as
the final step.
Fixes QubesOS/qubes-issues#5369
=> Cleanup parent xenstore dir after device remove

archlinux/PKGBUILD
autoreconf complains and fails to generate the configure script:
```
configure.ac: error: required file 'install-sh' not found
configure.ac:   try running autoreconf --install
```
Archlinux uses autoconf 2.70 as of 2020-12-24 which adds the `--install` option. This change in autoconf behavior is documented under "Noteworthy changes in release 2.70 / More macros use config.sub and config.guess internally" in the autoconf  NEWS[1].
[1]: https://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob_plain;f=NEWS;hb=HEAD
=> archlinux: fix autoreconf fail on autoconf 2.70

debian-vm/debian/xen-utils-common.xen.init, patch-xen-hotplug-external-store.patch
The former is a symlink to the latter and is longer.  No point in using
it.
=> Mass replace: ‘/var/run’ → ‘/run’

patch-0001-libxl-conditionally-allow-PCI-passthrough-on-PV-with.patch, xen.spec.in
Look for qubes.enable_insecure_pv_passthrough on dom0 kernel cmdline. If
it's present, allow creating PV domain with PCI devices even if IOMMU is
not present/enabled.
QubesOS/qubes-issues#5529
=> Add a patch for conditional IOMMU-less passthrough on PV domain

patch-gcc11-fixes.patch, series-vm.conf
Without this patch, builds of the Archlinux package fail: [build-error.log](https://github.com/QubesOS/qubes-vmm-xen/files/6548501/build-error.log)
The patch was copied from https://src.fedoraproject.org/rpms/xen/blob/rawhide/f/xen.gcc11.fixes.patch - I found the link from some discussions and it seems to work, but I don't actually understand the problems or fixes :man_shrugging:
=> Add a patch with gcc11 fixes

xen.modules-load.conf
We have newer systemd now with the -ENODEV handling fixed.
This reverts commit 893fefac99467f4612b5879b737ed2a5ee1cda57.
Fixes QubesOS/qubes-issues#6465
=> Revert "rpm: do not load xen-acpi-processor with systemd-modules-load"

patch-libxl-do-not-require-filling-backend_domid-to-remove.patch, xen.spec.in
libvirt does not set backend_domid when detaching a disk device (it does
backend_name, but it isn't resolved on detach). Instead of resolving the
backend_name, use other information (that is sufficient already) to
deduce backend_domid.
The patch is upstreamable, but likely only after Xen 4.16 will be
released (as in: after the pre-release code freeze).
Fixes QubesOS/qubes-issues#6996
=> libxl: correctly detect backend_domid when detaching a device

xen.spec.in
=> spec: install missing auxiliary files for autoreconf

patch-Always-allocate-domid-sequentially-and-do-not-reuse-.patch, xen.spec.in
When Xen runs out of domid to allocate, require a system reboot, instead
of reusing them.
=> Prohibit domid reuse

patch-libxl-add-pcidevs-to-stubdomain-earlier.patch, xen.spec.in
When stubdomain is constructed, PCI devices were added during qemu
startup (via hotplug path). While it makes the code (slightly) simpler,
as it's more similar to no-stubdomain case, it also causes problems:
- race condition during stubdomain startup (QEMU trying to access sysfs
entries before xen-pcifront materialize them): QubesOS/qubes-issues#6203
- absent 0000:00:00.0 (host bridge) device during QEMU startup, which
breaks `igd-passthru=on` case: QubesOS/qubes-issues#7164
While the first issue has alternative solution (retrying on failure),
the second does not. In this case, QEMU tries to copy few parameters
from the host bridge (apparently necessary for some drivers, although
doesn't seem to affect Linux), even though only IGD is assigned. While
0000:00:00.0 in (PV) stubdomain is not …
=> libxl: add pcidevs to stubdomain earlier

.gitmodules
I am getting the "connection reset by peer" erros when trying to fetch the git submodules:
```
-> Cloning qubes-vm-xen git repo...
Cloning into bare repository '/home/user/Repos/aur/qubes/qubes-vm-xen/qubes-vm-xen'...
remote: Enumerating objects: 7137, done.
remote: Counting objects: 100% (685/685), done.
remote: Compressing objects: 100% (388/388), done.
remote: Total 7137 (delta 311), reused 647 (delta 289), pack-reused 6452
Receiving objects: 100% (7137/7137), 6.10 MiB | 3.92 MiB/s, done.
Resolving deltas: 100% (3518/3518), done.
==> Validating source files with sha512sums...
qubes-vm-xen ... Skipped
==> Verifying source file signatures with gpg...
qubes-vm-xen git repo ... Passed
==> Extracting sources...
-> Creating working copy of qubes-vm-xen git repo...
Cloning into …
```
=> modules: use https instead of old git:// protocol

Makefile.builder
=> Makefile.builder: restrict build for BACKEND_VMM=xen

patch-gvt-hvmloader.patch, patch-gvt-hypercall-XENMEM_get_mfn_from_pfn.patch, patch-gvt-libxl-init.patch, xen.spec.in
This requires to add minimal support Intel GVT-g mediated passtrough
to Qubes OS. This patches based on Intel XenGT preview, XCP-NG
Project.
=> TBD: Add partially Intel GVT-g support (xengt device)

patch-x86-pv-Inject-GP-for-implicit-grant-unmaps.patch, xen.spec.in
Backport "x86/pv: Inject #GP for implicit grant unmaps" patch
QubesOS/qubes-issues#7631
=> Ease debugging gntdev driver failures

patch-Linux-loop-use-direct-io.patch, patch-xen-hotplug-external-store.patch, series-debian-vm.conf, series-vm.conf, xen.spec.in
This is a huge performance improvement for two reasons:
1. It uses the filesystem’s asynchronous I/O support, rather than using
synchronous I/O.
2. It bypasses the page cache, removing a redundant layer of caching and
associated overhead.
I also took the opportunity to rip out some cruft related to old losetup
versions, which Qubes OS doesn't need to support anymore.
Fixes QubesOS/qubes-issues#7332.
Marking as draft because I have not tested this yet, and there is the possibility that it could break something.
=> Use direct I/O for loop devices

0301-Relocate-the-ESRT-when-booting-via-multiboot2.patch, 0626-Validate-EFI-memory-descriptors.patch, xen.spec.in
It turns out that these can be invalid in various ways.  Based on code Ard Biesheuvel contributed for Linux.
=> Validate EFI memory descriptors

0301-x86-mm-shadow-avoid-assuming-a-specific-Xen-PAT.patch, 0302-x86-mm-shadow-do-not-open-code-PAGE_CACHE_ATTRS.patch, 0303-p2m-pt-Avoid-hard-coding-Xen-s-PAT.patch, 0304-efi-Avoid-hard-coding-the-various-PAT-constants.patch, 0305-x86-Add-memory-type-constants.patch, 0306-x86-Replace-PAT_-with-X86_MT_.patch, 0307-x86-Replace-MTRR_-constants-with-X86_MT_-constants.patch, 0308-x86-Replace-EPT_EMT_-constants-with-X86_MT_.patch, 0309-x86-Derive-XEN_MSR_PAT-from-its-individual-entries.patch, xen.spec.in
They are prerequisites for subsequent PAT changes that Qubes might also want to backport, and (unlike the others) have already been comitted upstream.
=> Backport PAT changes from Xen git master

xen.spec.in
Grub2 in R4.2 is made to include grub.cfg from primary /boot partition,
even on EFI systems - so it always lives in the same place. Do not not
override the config stub.
QubesOS/qubes-issues#7985
=> Do not override stub grub.cfg on EFI partition

0631-cpufreq-Allow-restricting-to-internal-governors-only.patch, 0632-cpufreq-Add-perf_freq-to-cpuinfo.patch, 0633-cpufreq-Export-intel_feature_detect.patch, 0634-cpufreq-Add-Hardware-P-State-HWP-driver.patch, 0635-xenpm-Change-get-cpufreq-para-output-for-internal.patch, 0636-cpufreq-Export-HWP-parameters-to-userspace.patch, 0637-libxc-Include-hwp_para-in-definitions.patch, 0638-xenpm-Print-HWP-parameters.patch, 0639-xen-Add-SET_CPUFREQ_HWP-xen_sysctl_pm_op.patch, 0640-libxc-Add-xc_set_cpufreq_hwp.patch, 0641-xenpm-Factor-out-a-non-fatal-cpuid_parse-variant.patch, 0642-xenpm-Add-set-cpufreq-hwp-subcommand.patch, 0643-cpufreq-enable-HWP-by-default.patch, xen.spec.in
Hardware-managed P-states (when supported) results significantly smaller
power consumption according to some user reports.
Fixes QubesOS/qubes-issues#4604
@jandryuk thanks for making the patches (2 years ago...)!
I made some minor changes, especially:
- dropped "fast MSR" thing, as it appears to apply to Ice Lake only, and has
no reliable discovery method on others
- dropped bumping XEN_SYSCTL_INTERFACE_VERSION, as the new union member is guarded with governor name anyway, and the overall structure size hasn't changed
- fixed default state in documentation
=> Include support for Intel HWP

1020-xen-tell-guests-what-speculative-workarounds-are-not.patch, xen.spec.in
Tell guest kernel what fixes are already available in the hardware, so
it can turn off some of the workarounds. This especially helps on newer
CPUs.
=> Recover some performance from unneeded speculative workarounds

0630-Drop-ELF-notes-from-non-EFI-binary-too.patch, xen.spec.in
The ELF notes on multiboot binary are broken, remove them to unbreak
booting from Heads (via kexec). See patch description for details.
Fixes QubesOS/qubes-issues#8032
=> Drop extra ELF notes

patch-0001-libxc-fix-compilation-error-with-gcc13.patch, series-vm.conf
This closes https://github.com/QubesOS/qubes-issues/issues/8208. Arch Linux [now uses `gcc 13.1.1-1`](https://archlinux.org/packages/core/x86_64/gcc/), which has among [its C changes](https://gcc.gnu.org/gcc-13/changes.html) this:
> New warnings:
>
> - [-Wenum-int-mismatch](https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/Warning-Options.html#index-Wenum-int-mismatch) warns about mismatches between an enumerated type and an integer type ([PR105131](https://gcc.gnu.org/PR105131))
So building `vmm-xen` on Arch now results in:
```
xc_psr.c:161:5: error: conflicting types for ‘xc_psr_cmt_get_data’ due to enum/integer mismatch; have ‘int(xc_interface *, uint32_t,  uint32_t,  xc_psr_cmt_type,  uint64_t *, uint64_t *)’ {aka ‘int(struct xc_interface_core *, unsigned int,  unsigned int, …
```
=> Fix build for GCC 13.1

xen.spec.in
The .annobin.notes section gets placed at the start of xen.efi, which
(for unclear reasons) breaks booting under OVMF with "Out of resources"
error message.
The section looks like this:
Idx Name          Size      VMA               LMA               File off  Algn
0 .annobin.notes 0001286a  ffff82d100000000  ffff82d100000000  00000480  2**2
CONTENTS, READONLY
=> Disable annobin for the hypervisor build

0653-libxl-Disable-relocating-memory-for-qemu-xen-in-stub.patch, xen.spec.in
backport fix for https://github.com/QubesOS/qubes-issues/issues/4321
mainly adjusted file path/name and offset in the patch
build tested
=> backport of libxl hvmloader fix

0670-x86-hpet-Disable-legacy-replacement-mode-after-test-.patch, 0671-x86-idle-Get-PC-8.10-counters-for-Tiger-and-Alder-La.patch, 0672-x86-ACPI-Ignore-entries-marked-as-unusable-when-pars.patch, 0673-x86-msr-Allow-hardware-domain-to-read-C-state-reside.patch, 0674-x86-mwait-idle-Use-ACPI-for-CPUs-without-hardcoded-C.patch, 0675-libxl_pci-Pass-power_mgmt-via-QMP.patch, xen.spec.in
This adds some basic support but even if working as intended this doesn't reach satisfactory residency values yet. And more importantly in Qubes' default configuration common devices (at least Intel integrated USB and Thunderbolt) need more work to not completely block residency.
https://github.com/QubesOS/qubes-issues/issues/6411
=> Basic S0ix support

0317-xen-list-add-LIST_HEAD_RO_AFTER_INIT.patch, 0318-x86-mm-add-API-for-marking-only-part-of-a-MMIO-page-.patch, 0319-drivers-char-Use-sub-page-ro-API-to-make-just-xhci-d.patch, xen.spec.in
Add patches fixing XHCI DbC console when sys-usb is running.
Technically not a backport yet, but this version is very close to beeing
committed upstream so should qualify as a backport soon.
=> Add XHCI DbC console fixes

0300-xen-list-add-LIST_HEAD_RO_AFTER_INIT.patch, 0301-x86-mm-add-API-for-marking-only-part-of-a-MMIO-page-.patch, 0302-drivers-char-Use-sub-page-ro-API-to-make-just-xhci-d.patch, xen.spec.in
Re-add patches fixing XHCI DbC console when sys-usb is running, as they
haven't made it to Xen 4.19.
See 1d786afc9ccb2372461a478d386d45032733297f for more context.
=> Re-add XHCI DbC console fixes

xen.spec.in
This fixes two bugs:
1. The bundled OVMF didn't support Xen, so UEFI guests failed to boot.
2. The bundled OVMF didn't include the license text alongside it.
Fixes: QubesOS/qubes-issues#8625
=> Depend on edk2-ovmf-xen instead of bundling OVMF

xen.spec.in
Avoid expanding macros in comments.
=> rpm: use %dnl to comment lines with macros
